{
 "title": "TrendSpider Microservices",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "/alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Alerts, getHistory timing",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(alerts_mdc_getData_seconds_bucket[5m])"
    }
   ]
  },
  { "title": "Datafeed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Requests per Hour",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(datafeed_barcharts_ddfplus[1h])",
     "legendFormat": "BC Req/1h"
    },
    {}
   ]
  },
  {
   "title": "GetHistory timing",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 10 },
   "targets": [
    {
     "expr": "rate(datafeed_history_seconds_bucket[5m])"
    }
   ]
  },
  {
   "title": "Resolve, timing",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "rate(datafeed_resolve_symbol_seconds_bucket[5m])"
    }
   ]
  }
 ]
}